dist: bionic

language: go

addons:
  apt:
    packages:
    - upx-ucl

go:
  - master

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

before_install: true

git:
  depth: 1

install: true
 
script:
  - go get -v ./...
  - go get -v github.com/go-bindata/go-bindata/...
  - export BUILD_DATE=$(date +'%Y%m%d%H%M%S')
  - export GIT_COMMIT=$(shell git rev-parse HEAD)
  - export GIT_DIRTY=$(shell test -n "`git status --porcelain`" && echo "+CHANGES" || true)
  - export CGO_ENABLED="0"
  - go generate
  - python3 gox.py -osarch="linux/386 linux/amd64 linux/arm linux/arm64 darwin/amd64 windows/amd64 windows/386" -output "build/{{.Dir}}_{{.OS}}_{{.Arch}}" -ldflags "-X github.com/slurdge/goeland/version.GitCommit=${GIT_COMMIT}${GIT_DIRTY} -X github.com/slurdge/goeland/version.BuildDate=${BUILD_DATE} -X github.com/slurdge/goeland/internal/goeland/fetch.clientID=${IMGUR_CLIENT_ID}"

before_deploy:
  - upx -9 ./build/*

deploy:
  provider: releases
  api_key: ${GITHUB_DEPLOY_TOKEN}
  file: build/*
  file_glob: true
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    on_success: change
    on_failure: always