language: go

go:
  - master

before_install:
  - go get github.com/mitchellh/gox

git:
  depth: 1

install:
  - go get -v ./...
  - export BUILD_DATE=$(date +'%Y%m%d%H%M%S')
  - export GIT_COMMIT=$(shell git rev-parse HEAD)
  - export GIT_DIRTY=$(shell test -n "`git status --porcelain`" && echo "+CHANGES" || true)
 
script:
  - gox -os="linux darwin windows" -arch="amd64 arm 386" -output "build/{{.Dir}}_{{.OS}}_{{.Arch}}" -ldflags "-X github.com/slurdge/goeland/version.GitCommit=${GIT_COMMIT}${GIT_DIRTY} -X github.com/slurdge/goeland/version.BuildDate=${BUILD_DATE} -s -w"

deploy:
  provider: releases
  api_key: ${GITHUB_DEPLOY_TOKEN}
  file: build/*
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    on_success: change
    on_failure: always