name: Build all supported platforms

on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name Setup
      uses: actions/checkout@v3
      uses: actions/setup-go@v3
      with:
        go-version: 1.16
      uses: actions/setup-python@v4
      with:
        python-version: 3.10
        architecture: 'x64'
    
    - name: Get Go Deps
      run: go get -v ./...

    - name: Build
      run: python3 gox.py -osarch="linux/386 linux/amd64 linux/arm linux/arm64 darwin/amd64 windows/amd64 windows/386" -output "build/{{.Dir}}_{{.OS}}_{{.Arch}}" -ldflags "-X github.com/slurdge/goeland/version.GitCommit=${GIT_COMMIT}${GIT_DIRTY} -X github.com/slurdge/goeland/version.BuildDate=${BUILD_DATE} -X github.com/slurdge/goeland/internal/goeland/fetch.clientID=${IMGUR_CLIENT_ID}"

