name: Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          package-name: release-please-action
          token: ${{ secrets.RELEASE_TOKEN }}