name: Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: go
          package-name: release-please-action
          include-v-in-tag: true
          token: ${{ secrets.RELEASE_TOKEN }}